using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Markup;
/*!
 *  Font Awesome 4.7.0 by @davegandy _ http://fontawesome.io _ @fontawesome
 *  License _ http://fontawesome.io/license (Font: SIL OFL 1.1; CSS: MIT License)
 */

/* Font Awesome uses the Unicode Private Use Area (PUA) to ensure screen
   readers do not read off random characters that represent icons */

/*总共675个图标*/
namespace WPFExpress.Fonts
{
    /// <summary>
    /// FontAwesome字体xaml扩展
    /// </summary>
    public class FontAwesome : MarkupExtension
    {
        //public FontAwesome(FontAwesomeType font)
        //{
        //    this.Font = font;
        //}
        public FontAwesomeType Font { get; set; }

        public override object ProvideValue(IServiceProvider serviceProvider)
        {
            Type t = typeof(FontAwesomeType);
            FieldInfo info = t.GetField(Font.ToString());
            if (info != null)
            {
                FontAwesomeCodeAttribute attr =Attribute.GetCustomAttribute(info,typeof(FontAwesomeCodeAttribute)) as FontAwesomeCodeAttribute;
                if (attr != null)
                    return attr.Value;
            }

            return null;
        }
    }
    [AttributeUsage(AttributeTargets.Field)]
    internal class FontAwesomeCodeAttribute : Attribute
    {
        public string Value { get; private set; }

        public FontAwesomeCodeAttribute(string value)
        {
            this.Value = value;
        }
    }

    //原始字体字符串xaml直接绑定
    // fa_music ="&#xf001;";

    //代码设置字体图标
    //this.ticon1.Text =\ue616";



    /// <summary>
    /// FontAwesome字体
    /// </summary>
    public enum FontAwesomeType
    {
        [FontAwesomeCode("\uf000")]
        fa_glass,
        [FontAwesomeCode("\uf001")]
        fa_music,
        [FontAwesomeCode("\uf002")]
        fa_search,
        [FontAwesomeCode("\uf003")]
        fa_envelope_o,
        [FontAwesomeCode("\uf004")]
        fa_heart,
        [FontAwesomeCode("\uf005")]
        fa_star,
        [FontAwesomeCode("\uf006")]
        fa_star_o,
        [FontAwesomeCode("\uf007")]
        fa_user,
        [FontAwesomeCode("\uf008")]
        fa_film,
        [FontAwesomeCode("\uf009")]
        fa_th_large,
        [FontAwesomeCode("\uf00a")]
        fa_th,
        [FontAwesomeCode("\uf00b")]
        fa_th_list,
        [FontAwesomeCode("\uf00c")]
        fa_check,
        [FontAwesomeCode("\uf00d")]
        fa_remove,
        [FontAwesomeCode("\uf00d")]
        fa_close,
        [FontAwesomeCode("\uf00d")]
        fa_times,
        [FontAwesomeCode("\uf00e")]
        fa_search_plus,
        [FontAwesomeCode("\uf010")]
        fa_search_minus,
        [FontAwesomeCode("\uf011")]
        fa_power_off,
        [FontAwesomeCode("\uf012")]
        fa_signal,
        [FontAwesomeCode("\uf013")]
        fa_gear,
        [FontAwesomeCode("\uf013")]
        fa_cog,
        [FontAwesomeCode("\uf014")]
        fa_trash_o,
        [FontAwesomeCode("\uf015")]
        fa_home,
        [FontAwesomeCode("\uf016")]
        fa_file_o,
        [FontAwesomeCode("\uf017")]
        fa_clock_o,
        [FontAwesomeCode("\uf018")]
        fa_road,
        [FontAwesomeCode("\uf019")]
        fa_download,
        [FontAwesomeCode("\uf01a")]
        fa_arrow_circle_o_down,
        [FontAwesomeCode("\uf01b")]
        fa_arrow_circle_o_up,
        [FontAwesomeCode("\uf01c")]
        fa_inbox,
        [FontAwesomeCode("\uf01d")]
        fa_play_circle_o,
        [FontAwesomeCode("\uf01e")]
        fa_rotate_right,
        [FontAwesomeCode("\uf01e")]
        fa_repeat,
        [FontAwesomeCode("\uf021")]
        fa_refresh,
        [FontAwesomeCode("\uf022")]
        fa_list_alt,
        [FontAwesomeCode("\uf023")]
        fa_lock,
        [FontAwesomeCode("\uf024")]
        fa_flag,
        [FontAwesomeCode("\uf025")]
        fa_headphones,
        [FontAwesomeCode("\uf026")]
        fa_volume_off,
        [FontAwesomeCode("\uf027")]
        fa_volume_down,
        [FontAwesomeCode("\uf028")]
        fa_volume_up,
        [FontAwesomeCode("\uf029")]
        fa_qrcode,
        [FontAwesomeCode("\uf02a")]
        fa_barcode,
        [FontAwesomeCode("\uf02b")]
        fa_tag,
        [FontAwesomeCode("\uf02c")]
        fa_tags,
        [FontAwesomeCode("\uf02d")]
        fa_book,
        [FontAwesomeCode("\uf02e")]
        fa_bookmark,
        [FontAwesomeCode("\uf02f")]
        fa_print,
        [FontAwesomeCode("\uf030")]
        fa_camera,
        [FontAwesomeCode("\uf031")]
        fa_font,
        [FontAwesomeCode("\uf032")]
        fa_bold,
        [FontAwesomeCode("\uf033")]
        fa_italic,
        [FontAwesomeCode("\uf034")]
        fa_text_height,
        [FontAwesomeCode("\uf035")]
        fa_text_width,
        [FontAwesomeCode("\uf036")]
        fa_align_left,
        [FontAwesomeCode("\uf037")]
        fa_align_center,
        [FontAwesomeCode("\uf038")]
        fa_align_right,
        [FontAwesomeCode("\uf039")]
        fa_align_justify,
        [FontAwesomeCode("\uf03a")]
        fa_list,
        [FontAwesomeCode("\uf03b")]
        fa_dedent,
        [FontAwesomeCode("\uf03b")]
        fa_outdent,
        [FontAwesomeCode("\uf03c")]
        fa_indent,
        [FontAwesomeCode("\uf03d")]
        fa_video_camera,
        [FontAwesomeCode("\uf03e")]
        fa_photo,
        [FontAwesomeCode("\uf03e")]
        fa_image,
        [FontAwesomeCode("\uf03e")]
        fa_picture_o,
        [FontAwesomeCode("\uf040")]
        fa_pencil,
        [FontAwesomeCode("\uf041")]
        fa_map_marker,
        [FontAwesomeCode("\uf042")]
        fa_adjust,
        [FontAwesomeCode("\uf043")]
        fa_tint,
        [FontAwesomeCode("\uf044")]
        fa_edit,
        [FontAwesomeCode("\uf044")]
        fa_pencil_square_o,
        [FontAwesomeCode("\uf045")]
        fa_share_square_o,
        [FontAwesomeCode("\uf046")]
        fa_check_square_o,
        [FontAwesomeCode("\uf047")]
        fa_arrows,
        [FontAwesomeCode("\uf048")]
        fa_step_backward,
        [FontAwesomeCode("\uf049")]
        fa_fast_backward,
        [FontAwesomeCode("\uf04a")]
        fa_backward,
        [FontAwesomeCode("\uf04b")]
        fa_play,
        [FontAwesomeCode("\uf04c")]
        fa_pause,
        [FontAwesomeCode("\uf04d")]
        fa_stop,
        [FontAwesomeCode("\uf04e")]
        fa_forward,
        [FontAwesomeCode("\uf050")]
        fa_fast_forward,
        [FontAwesomeCode("\uf051")]
        fa_step_forward,
        [FontAwesomeCode("\uf052")]
        fa_eject,
        [FontAwesomeCode("\uf053")]
        fa_chevron_left,
        [FontAwesomeCode("\uf054")]
        fa_chevron_right,
        [FontAwesomeCode("\uf055")]
        fa_plus_circle,
        [FontAwesomeCode("\uf056")]
        fa_minus_circle,
        [FontAwesomeCode("\uf057")]
        fa_times_circle,
        [FontAwesomeCode("\uf058")]
        fa_check_circle,
        [FontAwesomeCode("\uf059")]
        fa_question_circle,
        [FontAwesomeCode("\uf05a")]
        fa_info_circle,
        [FontAwesomeCode("\uf05b")]
        fa_crosshairs,
        [FontAwesomeCode("\uf05c")]
        fa_times_circle_o,
        [FontAwesomeCode("\uf05d")]
        fa_check_circle_o,
        [FontAwesomeCode("\uf05e")]
        fa_ban,
        [FontAwesomeCode("\uf060")]
        fa_arrow_left,
        [FontAwesomeCode("\uf061")]
        fa_arrow_right,
        [FontAwesomeCode("\uf062")]
        fa_arrow_up,
        [FontAwesomeCode("\uf063")]
        fa_arrow_down,
        [FontAwesomeCode("\uf064")]
        fa_mail_forward,
        [FontAwesomeCode("\uf064")]
        fa_share,
        [FontAwesomeCode("\uf065")]
        fa_expand,
        [FontAwesomeCode("\uf066")]
        fa_compress,
        [FontAwesomeCode("\uf067")]
        fa_plus,
        [FontAwesomeCode("\uf068")]
        fa_minus,
        [FontAwesomeCode("\uf069")]
        fa_asterisk,
        [FontAwesomeCode("\uf06a")]
        fa_exclamation_circle,
        [FontAwesomeCode("\uf06b")]
        fa_gift,
        [FontAwesomeCode("\uf06c")]
        fa_leaf,
        [FontAwesomeCode("\uf06d")]
        fa_fire,
        [FontAwesomeCode("\uf06e")]
        fa_eye,
        [FontAwesomeCode("\uf070")]
        fa_eye_slash,
        [FontAwesomeCode("\uf071")]
        fa_warning,
        [FontAwesomeCode("\uf071")]
        fa_exclamation_triangle,
        [FontAwesomeCode("\uf072")]
        fa_plane,
        [FontAwesomeCode("\uf073")]
        fa_calendar,
        [FontAwesomeCode("\uf074")]
        fa_random,
        [FontAwesomeCode("\uf075")]
        fa_comment,
        [FontAwesomeCode("\uf076")]
        fa_magnet,
        [FontAwesomeCode("\uf077")]
        fa_chevron_up,
        [FontAwesomeCode("\uf078")]
        fa_chevron_down,
        [FontAwesomeCode("\uf079")]
        fa_retweet,
        [FontAwesomeCode("\uf07a")]
        fa_shopping_cart,
        [FontAwesomeCode("\uf07b")]
        fa_folder,
        [FontAwesomeCode("\uf07c")]
        fa_folder_open,
        [FontAwesomeCode("\uf07d")]
        fa_arrows_v,
        [FontAwesomeCode("\uf07e")]
        fa_arrows_h,
        [FontAwesomeCode("\uf080")]
        fa_bar_chart_o,
        [FontAwesomeCode("\uf080")]
        fa_bar_chart,
        [FontAwesomeCode("\uf081")]
        fa_twitter_square,
        [FontAwesomeCode("\uf082")]
        fa_facebook_square,
        [FontAwesomeCode("\uf083")]
        fa_camera_retro,
        [FontAwesomeCode("\uf084")]
        fa_key,
        [FontAwesomeCode("\uf085")]
        fa_gears,
        [FontAwesomeCode("\uf085")]
        fa_cogs,
        [FontAwesomeCode("\uf086")]
        fa_comments,
        [FontAwesomeCode("\uf087")]
        fa_thumbs_o_up,
        [FontAwesomeCode("\uf088")]
        fa_thumbs_o_down,
        [FontAwesomeCode("\uf089")]
        fa_star_half,
        [FontAwesomeCode("\uf08a")]
        fa_heart_o,
        [FontAwesomeCode("\uf08b")]
        fa_sign_out,
        [FontAwesomeCode("\uf08c")]
        fa_linkedin_square,
        [FontAwesomeCode("\uf08d")]
        fa_thumb_tack,
        [FontAwesomeCode("\uf08e")]
        fa_external_link,
        [FontAwesomeCode("\uf090")]
        fa_sign_in,
        [FontAwesomeCode("\uf091")]
        fa_trophy,
        [FontAwesomeCode("\uf092")]
        fa_github_square,
        [FontAwesomeCode("\uf093")]
        fa_upload,
        [FontAwesomeCode("\uf094")]
        fa_lemon_o,
        [FontAwesomeCode("\uf095")]
        fa_phone,
        [FontAwesomeCode("\uf096")]
        fa_square_o,
        [FontAwesomeCode("\uf097")]
        fa_bookmark_o,
        [FontAwesomeCode("\uf098")]
        fa_phone_square,
        [FontAwesomeCode("\uf099")]
        fa_twitter,
        [FontAwesomeCode("\uf09a")]
        fa_facebook_f,
        [FontAwesomeCode("\uf09a")]
        fa_facebook,
        [FontAwesomeCode("\uf09b")]
        fa_github,
        [FontAwesomeCode("\uf09c")]
        fa_unlock,
        [FontAwesomeCode("\uf09d")]
        fa_credit_card,
        [FontAwesomeCode("\uf09e")]
        fa_feed,
        [FontAwesomeCode("\uf09e")]
        fa_rss,
        [FontAwesomeCode("\uf0a0")]
        fa_hdd_o,
        [FontAwesomeCode("\uf0a1")]
        fa_bullhorn,
        [FontAwesomeCode("\uf0f3")]
        fa_bell,
        [FontAwesomeCode("\uf0a3")]
        fa_certificate,
        [FontAwesomeCode("\uf0a4")]
        fa_hand_o_right,
        [FontAwesomeCode("\uf0a5")]
        fa_hand_o_left,
        [FontAwesomeCode("\uf0a6")]
        fa_hand_o_up,
        [FontAwesomeCode("\uf0a7")]
        fa_hand_o_down,
        [FontAwesomeCode("\uf0a8")]
        fa_arrow_circle_left,
        [FontAwesomeCode("\uf0a9")]
        fa_arrow_circle_right,
        [FontAwesomeCode("\uf0aa")]
        fa_arrow_circle_up,
        [FontAwesomeCode("\uf0ab")]
        fa_arrow_circle_down,
        [FontAwesomeCode("\uf0ac")]
        fa_globe,
        [FontAwesomeCode("\uf0ad")]
        fa_wrench,
        [FontAwesomeCode("\uf0ae")]
        fa_tasks,
        [FontAwesomeCode("\uf0b0")]
        fa_filter,
        [FontAwesomeCode("\uf0b1")]
        fa_briefcase,
        [FontAwesomeCode("\uf0b2")]
        fa_arrows_alt,
        [FontAwesomeCode("\uf0c0")]
        fa_group,
        [FontAwesomeCode("\uf0c0")]
        fa_users,
        [FontAwesomeCode("\uf0c1")]
        fa_chain,
        [FontAwesomeCode("\uf0c1")]
        fa_link,
        [FontAwesomeCode("\uf0c2")]
        fa_cloud,
        [FontAwesomeCode("\uf0c3")]
        fa_flask,
        [FontAwesomeCode("\uf0c4")]
        fa_cut,
        [FontAwesomeCode("\uf0c4")]
        fa_scissors,
        [FontAwesomeCode("\uf0c5")]
        fa_copy,
        [FontAwesomeCode("\uf0c5")]
        fa_files_o,
        [FontAwesomeCode("\uf0c6")]
        fa_paperclip,
        [FontAwesomeCode("\uf0c7")]
        fa_save,
        [FontAwesomeCode("\uf0c7")]
        fa_floppy_o,
        [FontAwesomeCode("\uf0c8")]
        fa_square,
        [FontAwesomeCode("\uf0c9")]
        fa_navicon,
        [FontAwesomeCode("\uf0c9")]
        fa_reorder,
        [FontAwesomeCode("\uf0c9")]
        fa_bars,
        [FontAwesomeCode("\uf0ca")]
        fa_list_ul,
        [FontAwesomeCode("\uf0cb")]
        fa_list_ol,
        [FontAwesomeCode("\uf0cc")]
        fa_strikethrough,
        [FontAwesomeCode("\uf0cd")]
        fa_underline,
        [FontAwesomeCode("\uf0ce")]
        fa_table,
        [FontAwesomeCode("\uf0d0")]
        fa_magic,
        [FontAwesomeCode("\uf0d1")]
        fa_truck,
        [FontAwesomeCode("\uf0d2")]
        fa_pinterest,
        [FontAwesomeCode("\uf0d3")]
        fa_pinterest_square,
        [FontAwesomeCode("\uf0d4")]
        fa_google_plus_square,
        [FontAwesomeCode("\uf0d5")]
        fa_google_plus,
        [FontAwesomeCode("\uf0d6")]
        fa_money,
        [FontAwesomeCode("\uf0d7")]
        fa_caret_down,
        [FontAwesomeCode("\uf0d8")]
        fa_caret_up,
        [FontAwesomeCode("\uf0d9")]
        fa_caret_left,
        [FontAwesomeCode("\uf0da")]
        fa_caret_right,
        [FontAwesomeCode("\uf0db")]
        fa_columns,
        [FontAwesomeCode("\uf0dc")]
        fa_unsorted,
        [FontAwesomeCode("\uf0dc")]
        fa_sort,
        [FontAwesomeCode("\uf0dd")]
        fa_sort_down,
        [FontAwesomeCode("\uf0dd")]
        fa_sort_desc,
        [FontAwesomeCode("\uf0de")]
        fa_sort_up,
        [FontAwesomeCode("\uf0de")]
        fa_sort_asc,
        [FontAwesomeCode("\uf0e0")]
        fa_envelope,
        [FontAwesomeCode("\uf0e1")]
        fa_linkedin,
        [FontAwesomeCode("\uf0e2")]
        fa_rotate_left,
        [FontAwesomeCode("\uf0e2")]
        fa_undo,
        [FontAwesomeCode("\uf0e3")]
        fa_legal,
        [FontAwesomeCode("\uf0e3")]
        fa_gavel,
        [FontAwesomeCode("\uf0e4")]
        fa_dashboard,
        [FontAwesomeCode("\uf0e4")]
        fa_tachometer,
        [FontAwesomeCode("\uf0e5")]
        fa_comment_o,
        [FontAwesomeCode("\uf0e6")]
        fa_comments_o,
        [FontAwesomeCode("\uf0e7")]
        fa_flash,
        [FontAwesomeCode("\uf0e7")]
        fa_bolt,
        [FontAwesomeCode("\uf0e8")]
        fa_sitemap,
        [FontAwesomeCode("\uf0e9")]
        fa_umbrella,
        [FontAwesomeCode("\uf0ea")]
        fa_paste,
        [FontAwesomeCode("\uf0ea")]
        fa_clipboard,
        [FontAwesomeCode("\uf0eb")]
        fa_lightbulb_o,
        [FontAwesomeCode("\uf0ec")]
        fa_exchange,
        [FontAwesomeCode("\uf0ed")]
        fa_cloud_download,
        [FontAwesomeCode("\uf0ee")]
        fa_cloud_upload,
        [FontAwesomeCode("\uf0f0")]
        fa_user_md,
        [FontAwesomeCode("\uf0f1")]
        fa_stethoscope,
        [FontAwesomeCode("\uf0f2")]
        fa_suitcase,
        [FontAwesomeCode("\uf0a2")]
        fa_bell_o,
        [FontAwesomeCode("\uf0f4")]
        fa_coffee,
        [FontAwesomeCode("\uf0f5")]
        fa_cutlery,
        [FontAwesomeCode("\uf0f6")]
        fa_file_text_o,
        [FontAwesomeCode("\uf0f7")]
        fa_building_o,
        [FontAwesomeCode("\uf0f8")]
        fa_hospital_o,
        [FontAwesomeCode("\uf0f9")]
        fa_ambulance,
        [FontAwesomeCode("\uf0fa")]
        fa_medkit,
        [FontAwesomeCode("\uf0fb")]
        fa_fighter_jet,
        [FontAwesomeCode("\uf0fc")]
        fa_beer,
        [FontAwesomeCode("\uf0fd")]
        fa_h_square,
        [FontAwesomeCode("\uf0fe")]
        fa_plus_square,
        [FontAwesomeCode("\uf100")]
        fa_angle_double_left,
        [FontAwesomeCode("\uf101")]
        fa_angle_double_right,
        [FontAwesomeCode("\uf102")]
        fa_angle_double_up,
        [FontAwesomeCode("\uf103")]
        fa_angle_double_down,
        [FontAwesomeCode("\uf104")]
        fa_angle_left,
        [FontAwesomeCode("\uf105")]
        fa_angle_right,
        [FontAwesomeCode("\uf106")]
        fa_angle_up,
        [FontAwesomeCode("\uf107")]
        fa_angle_down,
        [FontAwesomeCode("\uf108")]
        fa_desktop,
        [FontAwesomeCode("\uf109")]
        fa_laptop,
        [FontAwesomeCode("\uf10a")]
        fa_tablet,
        [FontAwesomeCode("\uf10b")]
        fa_mobile_phone,
        [FontAwesomeCode("\uf10b")]
        fa_mobile,
        [FontAwesomeCode("\uf10c")]
        fa_circle_o,
        [FontAwesomeCode("\uf10d")]
        fa_quote_left,
        [FontAwesomeCode("\uf10e")]
        fa_quote_right,
        [FontAwesomeCode("\uf110")]
        fa_spinner,
        [FontAwesomeCode("\uf111")]
        fa_circle,
        [FontAwesomeCode("\uf112")]
        fa_mail_reply,
        [FontAwesomeCode("\uf112")]
        fa_reply,
        [FontAwesomeCode("\uf113")]
        fa_github_alt,
        [FontAwesomeCode("\uf114")]
        fa_folder_o,
        [FontAwesomeCode("\uf115")]
        fa_folder_open_o,
        [FontAwesomeCode("\uf118")]
        fa_smile_o,
        [FontAwesomeCode("\uf119")]
        fa_frown_o,
        [FontAwesomeCode("\uf11a")]
        fa_meh_o,
        [FontAwesomeCode("\uf11b")]
        fa_gamepad,
        [FontAwesomeCode("\uf11c")]
        fa_keyboard_o,
        [FontAwesomeCode("\uf11d")]
        fa_flag_o,
        [FontAwesomeCode("\uf11e")]
        fa_flag_checkered,
        [FontAwesomeCode("\uf120")]
        fa_terminal,
        [FontAwesomeCode("\uf121")]
        fa_code,
        [FontAwesomeCode("\uf122")]
        fa_mail_reply_all,
        [FontAwesomeCode("\uf122")]
        fa_reply_all,
        [FontAwesomeCode("\uf123")]
        fa_star_half_empty,
        [FontAwesomeCode("\uf123")]
        fa_star_half_full,
        [FontAwesomeCode("\uf123")]
        fa_star_half_o,
        [FontAwesomeCode("\uf124")]
        fa_location_arrow,
        [FontAwesomeCode("\uf125")]
        fa_crop,
        [FontAwesomeCode("\uf126")]
        fa_code_fork,
        [FontAwesomeCode("\uf127")]
        fa_unlink,
        [FontAwesomeCode("\uf127")]
        fa_chain_broken,
        [FontAwesomeCode("\uf128")]
        fa_question,
        [FontAwesomeCode("\uf129")]
        fa_info,
        [FontAwesomeCode("\uf12a")]
        fa_exclamation,
        [FontAwesomeCode("\uf12b")]
        fa_superscript,
        [FontAwesomeCode("\uf12c")]
        fa_subscript,
        [FontAwesomeCode("\uf12d")]
        fa_eraser,
        [FontAwesomeCode("\uf12e")]
        fa_puzzle_piece,
        [FontAwesomeCode("\uf130")]
        fa_microphone,
        [FontAwesomeCode("\uf131")]
        fa_microphone_slash,
        [FontAwesomeCode("\uf132")]
        fa_shield,
        [FontAwesomeCode("\uf133")]
        fa_calendar_o,
        [FontAwesomeCode("\uf134")]
        fa_fire_extinguisher,
        [FontAwesomeCode("\uf135")]
        fa_rocket,
        [FontAwesomeCode("\uf136")]
        fa_maxcdn,
        [FontAwesomeCode("\uf137")]
        fa_chevron_circle_left,
        [FontAwesomeCode("\uf138")]
        fa_chevron_circle_right,
        [FontAwesomeCode("\uf139")]
        fa_chevron_circle_up,
        [FontAwesomeCode("\uf13a")]
        fa_chevron_circle_down,
        [FontAwesomeCode("\uf13b")]
        fa_html5,
        [FontAwesomeCode("\uf13c")]
        fa_css3,
        [FontAwesomeCode("\uf13d")]
        fa_anchor,
        [FontAwesomeCode("\uf13e")]
        fa_unlock_alt,
        [FontAwesomeCode("\uf140")]
        fa_bullseye,
        [FontAwesomeCode("\uf141")]
        fa_ellipsis_h,
        [FontAwesomeCode("\uf142")]
        fa_ellipsis_v,
        [FontAwesomeCode("\uf143")]
        fa_rss_square,
        [FontAwesomeCode("\uf144")]
        fa_play_circle,
        [FontAwesomeCode("\uf145")]
        fa_ticket,
        [FontAwesomeCode("\uf146")]
        fa_minus_square,
        [FontAwesomeCode("\uf147")]
        fa_minus_square_o,
        [FontAwesomeCode("\uf148")]
        fa_level_up,
        [FontAwesomeCode("\uf149")]
        fa_level_down,
        [FontAwesomeCode("\uf14a")]
        fa_check_square,
        [FontAwesomeCode("\uf14b")]
        fa_pencil_square,
        [FontAwesomeCode("\uf14c")]
        fa_external_link_square,
        [FontAwesomeCode("\uf14d")]
        fa_share_square,
        [FontAwesomeCode("\uf14e")]
        fa_compass,
        [FontAwesomeCode("\uf150")]
        fa_toggle_down,
        [FontAwesomeCode("\uf150")]
        fa_caret_square_o_down,
        [FontAwesomeCode("\uf151")]
        fa_toggle_up,
        [FontAwesomeCode("\uf151")]
        fa_caret_square_o_up,
        [FontAwesomeCode("\uf152")]
        fa_toggle_right,
        [FontAwesomeCode("\uf152")]
        fa_caret_square_o_right,
        [FontAwesomeCode("\uf153")]
        fa_euro,
        [FontAwesomeCode("\uf153")]
        fa_eur,
        [FontAwesomeCode("\uf154")]
        fa_gbp,
        [FontAwesomeCode("\uf155")]
        fa_dollar,
        [FontAwesomeCode("\uf155")]
        fa_usd,
        [FontAwesomeCode("\uf156")]
        fa_rupee,
        [FontAwesomeCode("\uf156")]
        fa_inr,
        [FontAwesomeCode("\uf157")]
        fa_cny,
        [FontAwesomeCode("\uf157")]
        fa_rmb,
        [FontAwesomeCode("\uf157")]
        fa_yen,
        [FontAwesomeCode("\uf157")]
        fa_jpy,
        [FontAwesomeCode("\uf158")]
        fa_ruble,
        [FontAwesomeCode("\uf158")]
        fa_rouble,
        [FontAwesomeCode("\uf158")]
        fa_rub,
        [FontAwesomeCode("\uf159")]
        fa_won,
        [FontAwesomeCode("\uf159")]
        fa_krw,
        [FontAwesomeCode("\uf15a")]
        fa_bitcoin,
        [FontAwesomeCode("\uf15a")]
        fa_btc,
        [FontAwesomeCode("\uf15b")]
        fa_file,
        [FontAwesomeCode("\uf15c")]
        fa_file_text,
        [FontAwesomeCode("\uf15d")]
        fa_sort_alpha_asc,
        [FontAwesomeCode("\uf15e")]
        fa_sort_alpha_desc,
        [FontAwesomeCode("\uf160")]
        fa_sort_amount_asc,
        [FontAwesomeCode("\uf161")]
        fa_sort_amount_desc,
        [FontAwesomeCode("\uf162")]
        fa_sort_numeric_asc,
        [FontAwesomeCode("\uf163")]
        fa_sort_numeric_desc,
        [FontAwesomeCode("\uf164")]
        fa_thumbs_up,
        [FontAwesomeCode("\uf165")]
        fa_thumbs_down,
        [FontAwesomeCode("\uf166")]
        fa_youtube_square,
        [FontAwesomeCode("\uf167")]
        fa_youtube,
        [FontAwesomeCode("\uf168")]
        fa_xing,
        [FontAwesomeCode("\uf169")]
        fa_xing_square,
        [FontAwesomeCode("\uf16a")]
        fa_youtube_play,
        [FontAwesomeCode("\uf16b")]
        fa_dropbox,
        [FontAwesomeCode("\uf16c")]
        fa_stack_overflow,
        [FontAwesomeCode("\uf16d")]
        fa_instagram,
        [FontAwesomeCode("\uf16e")]
        fa_flickr,
        [FontAwesomeCode("\uf170")]
        fa_adn,
        [FontAwesomeCode("\uf171")]
        fa_bitbucket,
        [FontAwesomeCode("\uf172")]
        fa_bitbucket_square,
        [FontAwesomeCode("\uf173")]
        fa_tumblr,
        [FontAwesomeCode("\uf174")]
        fa_tumblr_square,
        [FontAwesomeCode("\uf175")]
        fa_long_arrow_down,
        [FontAwesomeCode("\uf176")]
        fa_long_arrow_up,
        [FontAwesomeCode("\uf177")]
        fa_long_arrow_left,
        [FontAwesomeCode("\uf178")]
        fa_long_arrow_right,
        [FontAwesomeCode("\uf179")]
        fa_apple,
        [FontAwesomeCode("\uf17a")]
        fa_windows,
        [FontAwesomeCode("\uf17b")]
        fa_android,
        [FontAwesomeCode("\uf17c")]
        fa_linux,
        [FontAwesomeCode("\uf17d")]
        fa_dribbble,
        [FontAwesomeCode("\uf17e")]
        fa_skype,
        [FontAwesomeCode("\uf180")]
        fa_foursquare,
        [FontAwesomeCode("\uf181")]
        fa_trello,
        [FontAwesomeCode("\uf182")]
        fa_female,
        [FontAwesomeCode("\uf183")]
        fa_male,
        [FontAwesomeCode("\uf184")]
        fa_gittip,
        [FontAwesomeCode("\uf184")]
        fa_gratipay,
        [FontAwesomeCode("\uf185")]
        fa_sun_o,
        [FontAwesomeCode("\uf186")]
        fa_moon_o,
        [FontAwesomeCode("\uf187")]
        fa_archive,
        [FontAwesomeCode("\uf188")]
        fa_bug,
        [FontAwesomeCode("\uf189")]
        fa_vk,
        [FontAwesomeCode("\uf18a")]
        fa_weibo,
        [FontAwesomeCode("\uf18b")]
        fa_renren,
        [FontAwesomeCode("\uf18c")]
        fa_pagelines,
        [FontAwesomeCode("\uf18d")]
        fa_stack_exchange,
        [FontAwesomeCode("\uf18e")]
        fa_arrow_circle_o_right,
        [FontAwesomeCode("\uf190")]
        fa_arrow_circle_o_left,
        [FontAwesomeCode("\uf191")]
        fa_toggle_left,
        [FontAwesomeCode("\uf191")]
        fa_caret_square_o_left,
        [FontAwesomeCode("\uf192")]
        fa_dot_circle_o,
        [FontAwesomeCode("\uf193")]
        fa_wheelchair,
        [FontAwesomeCode("\uf194")]
        fa_vimeo_square,
        [FontAwesomeCode("\uf195")]
        fa_turkish_lira,
        [FontAwesomeCode("\uf195")]
        fa_try,
        [FontAwesomeCode("\uf196")]
        fa_plus_square_o,
        [FontAwesomeCode("\uf197")]
        fa_space_shuttle,
        [FontAwesomeCode("\uf198")]
        fa_slack,
        [FontAwesomeCode("\uf199")]
        fa_envelope_square,
        [FontAwesomeCode("\uf19a")]
        fa_wordpress,
        [FontAwesomeCode("\uf19b")]
        fa_openid,
        [FontAwesomeCode("\uf19c")]
        fa_institution,
        [FontAwesomeCode("\uf19c")]
        fa_bank,
        [FontAwesomeCode("\uf19c")]
        fa_university,
        [FontAwesomeCode("\uf19d")]
        fa_mortar_board,
        [FontAwesomeCode("\uf19d")]
        fa_graduation_cap,
        [FontAwesomeCode("\uf19e")]
        fa_yahoo,
        [FontAwesomeCode("\uf1a0")]
        fa_google,
        [FontAwesomeCode("\uf1a1")]
        fa_reddit,
        [FontAwesomeCode("\uf1a2")]
        fa_reddit_square,
        [FontAwesomeCode("\uf1a3")]
        fa_stumbleupon_circle,
        [FontAwesomeCode("\uf1a4")]
        fa_stumbleupon,
        [FontAwesomeCode("\uf1a5")]
        fa_delicious,
        [FontAwesomeCode("\uf1a6")]
        fa_digg,
        [FontAwesomeCode("\uf1a7")]
        fa_pied_piper_pp,
        [FontAwesomeCode("\uf1a8")]
        fa_pied_piper_alt,
        [FontAwesomeCode("\uf1a9")]
        fa_drupal,
        [FontAwesomeCode("\uf1aa")]
        fa_joomla,
        [FontAwesomeCode("\uf1ab")]
        fa_language,
        [FontAwesomeCode("\uf1ac")]
        fa_fax,
        [FontAwesomeCode("\uf1ad")]
        fa_building,
        [FontAwesomeCode("\uf1ae")]
        fa_child,
        [FontAwesomeCode("\uf1b0")]
        fa_paw,
        [FontAwesomeCode("\uf1b1")]
        fa_spoon,
        [FontAwesomeCode("\uf1b2")]
        fa_cube,
        [FontAwesomeCode("\uf1b3")]
        fa_cubes,
        [FontAwesomeCode("\uf1b4")]
        fa_behance,
        [FontAwesomeCode("\uf1b5")]
        fa_behance_square,
        [FontAwesomeCode("\uf1b6")]
        fa_steam,
        [FontAwesomeCode("\uf1b7")]
        fa_steam_square,
        [FontAwesomeCode("\uf1b8")]
        fa_recycle,
        [FontAwesomeCode("\uf1b9")]
        fa_automobile,
        [FontAwesomeCode("\uf1b9")]
        fa_car,
        [FontAwesomeCode("\uf1ba")]
        fa_cab,
        [FontAwesomeCode("\uf1ba")]
        fa_taxi,
        [FontAwesomeCode("\uf1bb")]
        fa_tree,
        [FontAwesomeCode("\uf1bc")]
        fa_spotify,
        [FontAwesomeCode("\uf1bd")]
        fa_deviantart,
        [FontAwesomeCode("\uf1be")]
        fa_soundcloud,
        [FontAwesomeCode("\uf1c0")]
        fa_database,
        [FontAwesomeCode("\uf1c1")]
        fa_file_pdf_o,
        [FontAwesomeCode("\uf1c2")]
        fa_file_word_o,
        [FontAwesomeCode("\uf1c3")]
        fa_file_excel_o,
        [FontAwesomeCode("\uf1c4")]
        fa_file_powerpoint_o,
        [FontAwesomeCode("\uf1c5")]
        fa_file_photo_o,
        [FontAwesomeCode("\uf1c5")]
        fa_file_picture_o,
        [FontAwesomeCode("\uf1c5")]
        fa_file_image_o,
        [FontAwesomeCode("\uf1c6")]
        fa_file_zip_o,
        [FontAwesomeCode("\uf1c6")]
        fa_file_archive_o,
        [FontAwesomeCode("\uf1c7")]
        fa_file_sound_o,
        [FontAwesomeCode("\uf1c7")]
        fa_file_audio_o,
        [FontAwesomeCode("\uf1c8")]
        fa_file_movie_o,
        [FontAwesomeCode("\uf1c8")]
        fa_file_video_o,
        [FontAwesomeCode("\uf1c9")]
        fa_file_code_o,
        [FontAwesomeCode("\uf1ca")]
        fa_vine,
        [FontAwesomeCode("\uf1cb")]
        fa_codepen,
        [FontAwesomeCode("\uf1cc")]
        fa_jsfiddle,
        [FontAwesomeCode("\uf1cd")]
        fa_life_bouy,
        [FontAwesomeCode("\uf1cd")]
        fa_life_buoy,
        [FontAwesomeCode("\uf1cd")]
        fa_life_saver,
        [FontAwesomeCode("\uf1cd")]
        fa_support,
        [FontAwesomeCode("\uf1cd")]
        fa_life_ring,
        [FontAwesomeCode("\uf1ce")]
        fa_circle_o_notch,
        [FontAwesomeCode("\uf1d0")]
        fa_ra,
        [FontAwesomeCode("\uf1d0")]
        fa_resistance,
        [FontAwesomeCode("\uf1d0")]
        fa_rebel,
        [FontAwesomeCode("\uf1d1")]
        fa_ge,
        [FontAwesomeCode("\uf1d1")]
        fa_empire,
        [FontAwesomeCode("\uf1d2")]
        fa_git_square,
        [FontAwesomeCode("\uf1d3")]
        fa_git,
        [FontAwesomeCode("\uf1d4")]
        fa_y_combinator_square,
        [FontAwesomeCode("\uf1d4")]
        fa_yc_square,
        [FontAwesomeCode("\uf1d4")]
        fa_hacker_news,
        [FontAwesomeCode("\uf1d5")]
        fa_tencent_weibo,
        [FontAwesomeCode("\uf1d6")]
        fa_qq,
        [FontAwesomeCode("\uf1d7")]
        fa_wechat,
        [FontAwesomeCode("\uf1d7")]
        fa_weixin,
        [FontAwesomeCode("\uf1d8")]
        fa_send,
        [FontAwesomeCode("\uf1d8")]
        fa_paper_plane,
        [FontAwesomeCode("\uf1d9")]
        fa_send_o,
        [FontAwesomeCode("\uf1d9")]
        fa_paper_plane_o,
        [FontAwesomeCode("\uf1da")]
        fa_history,
        [FontAwesomeCode("\uf1db")]
        fa_circle_thin,
        [FontAwesomeCode("\uf1dc")]
        fa_header,
        [FontAwesomeCode("\uf1dd")]
        fa_paragraph,
        [FontAwesomeCode("\uf1de")]
        fa_sliders,
        [FontAwesomeCode("\uf1e0")]
        fa_share_alt,
        [FontAwesomeCode("\uf1e1")]
        fa_share_alt_square,
        [FontAwesomeCode("\uf1e2")]
        fa_bomb,
        [FontAwesomeCode("\uf1e3")]
        fa_soccer_ball_o,
        [FontAwesomeCode("\uf1e3")]
        fa_futbol_o,
        [FontAwesomeCode("\uf1e4")]
        fa_tty,
        [FontAwesomeCode("\uf1e5")]
        fa_binoculars,
        [FontAwesomeCode("\uf1e6")]
        fa_plug,
        [FontAwesomeCode("\uf1e7")]
        fa_slideshare,
        [FontAwesomeCode("\uf1e8")]
        fa_twitch,
        [FontAwesomeCode("\uf1e9")]
        fa_yelp,
        [FontAwesomeCode("\uf1ea")]
        fa_newspaper_o,
        [FontAwesomeCode("\uf1eb")]
        fa_wifi,
        [FontAwesomeCode("\uf1ec")]
        fa_calculator,
        [FontAwesomeCode("\uf1ed")]
        fa_paypal,
        [FontAwesomeCode("\uf1ee")]
        fa_google_wallet,
        [FontAwesomeCode("\uf1f0")]
        fa_cc_visa,
        [FontAwesomeCode("\uf1f1")]
        fa_cc_mastercard,
        [FontAwesomeCode("\uf1f2")]
        fa_cc_discover,
        [FontAwesomeCode("\uf1f3")]
        fa_cc_amex,
        [FontAwesomeCode("\uf1f4")]
        fa_cc_paypal,
        [FontAwesomeCode("\uf1f5")]
        fa_cc_stripe,
        [FontAwesomeCode("\uf1f6")]
        fa_bell_slash,
        [FontAwesomeCode("\uf1f7")]
        fa_bell_slash_o,
        [FontAwesomeCode("\uf1f8")]
        fa_trash,
        [FontAwesomeCode("\uf1f9")]
        fa_copyright,
        [FontAwesomeCode("\uf1fa")]
        fa_at,
        [FontAwesomeCode("\uf1fb")]
        fa_eyedropper,
        [FontAwesomeCode("\uf1fc")]
        fa_paint_brush,
        [FontAwesomeCode("\uf1fd")]
        fa_birthday_cake,
        [FontAwesomeCode("\uf1fe")]
        fa_area_chart,
        [FontAwesomeCode("\uf200")]
        fa_pie_chart,
        [FontAwesomeCode("\uf201")]
        fa_line_chart,
        [FontAwesomeCode("\uf202")]
        fa_lastfm,
        [FontAwesomeCode("\uf203")]
        fa_lastfm_square,
        [FontAwesomeCode("\uf204")]
        fa_toggle_off,
        [FontAwesomeCode("\uf205")]
        fa_toggle_on,
        [FontAwesomeCode("\uf206")]
        fa_bicycle,
        [FontAwesomeCode("\uf207")]
        fa_bus,
        [FontAwesomeCode("\uf208")]
        fa_ioxhost,
        [FontAwesomeCode("\uf209")]
        fa_angellist,
        [FontAwesomeCode("\uf20a")]
        fa_cc,
        [FontAwesomeCode("\uf20b")]
        fa_shekel,
        [FontAwesomeCode("\uf20b")]
        fa_sheqel,
        [FontAwesomeCode("\uf20b")]
        fa_ils,
        [FontAwesomeCode("\uf20c")]
        fa_meanpath,
        [FontAwesomeCode("\uf20d")]
        fa_buysellads,
        [FontAwesomeCode("\uf20e")]
        fa_connectdevelop,
        [FontAwesomeCode("\uf210")]
        fa_dashcube,
        [FontAwesomeCode("\uf211")]
        fa_forumbee,
        [FontAwesomeCode("\uf212")]
        fa_leanpub,
        [FontAwesomeCode("\uf213")]
        fa_sellsy,
        [FontAwesomeCode("\uf214")]
        fa_shirtsinbulk,
        [FontAwesomeCode("\uf215")]
        fa_simplybuilt,
        [FontAwesomeCode("\uf216")]
        fa_skyatlas,
        [FontAwesomeCode("\uf217")]
        fa_cart_plus,
        [FontAwesomeCode("\uf218")]
        fa_cart_arrow_down,
        [FontAwesomeCode("\uf219")]
        fa_diamond,
        [FontAwesomeCode("\uf21a")]
        fa_ship,
        [FontAwesomeCode("\uf21b")]
        fa_user_secret,
        [FontAwesomeCode("\uf21c")]
        fa_motorcycle,
        [FontAwesomeCode("\uf21d")]
        fa_street_view,
        [FontAwesomeCode("\uf21e")]
        fa_heartbeat,
        [FontAwesomeCode("\uf221")]
        fa_venus,
        [FontAwesomeCode("\uf222")]
        fa_mars,
        [FontAwesomeCode("\uf223")]
        fa_mercury,
        [FontAwesomeCode("\uf224")]
        fa_intersex,
        [FontAwesomeCode("\uf224")]
        fa_transgender,
        [FontAwesomeCode("\uf225")]
        fa_transgender_alt,
        [FontAwesomeCode("\uf226")]
        fa_venus_double,
        [FontAwesomeCode("\uf227")]
        fa_mars_double,
        [FontAwesomeCode("\uf228")]
        fa_venus_mars,
        [FontAwesomeCode("\uf229")]
        fa_mars_stroke,
        [FontAwesomeCode("\uf22a")]
        fa_mars_stroke_v,
        [FontAwesomeCode("\uf22b")]
        fa_mars_stroke_h,
        [FontAwesomeCode("\uf22c")]
        fa_neuter,
        [FontAwesomeCode("\uf22d")]
        fa_genderless,
        [FontAwesomeCode("\uf230")]
        fa_facebook_official,
        [FontAwesomeCode("\uf231")]
        fa_pinterest_p,
        [FontAwesomeCode("\uf232")]
        fa_whatsapp,
        [FontAwesomeCode("\uf233")]
        fa_server,
        [FontAwesomeCode("\uf234")]
        fa_user_plus,
        [FontAwesomeCode("\uf235")]
        fa_user_times,
        [FontAwesomeCode("\uf236")]
        fa_hotel,
        [FontAwesomeCode("\uf236")]
        fa_bed,
        [FontAwesomeCode("\uf237")]
        fa_viacoin,
        [FontAwesomeCode("\uf238")]
        fa_train,
        [FontAwesomeCode("\uf239")]
        fa_subway,
        [FontAwesomeCode("\uf23a")]
        fa_medium,
        [FontAwesomeCode("\uf23b")]
        fa_yc,
        [FontAwesomeCode("\uf23b")]
        fa_y_combinator,
        [FontAwesomeCode("\uf23c")]
        fa_optin_monster,
        [FontAwesomeCode("\uf23d")]
        fa_opencart,
        [FontAwesomeCode("\uf23e")]
        fa_expeditedssl,
        [FontAwesomeCode("\uf240")]
        fa_battery_4,
        [FontAwesomeCode("\uf240")]
        fa_battery,
        [FontAwesomeCode("\uf240")]
        fa_battery_full,
        [FontAwesomeCode("\uf241")]
        fa_battery_3,
        [FontAwesomeCode("\uf241")]
        fa_battery_three_quarters,
        [FontAwesomeCode("\uf242")]
        fa_battery_2,
        [FontAwesomeCode("\uf242")]
        fa_battery_half,
        [FontAwesomeCode("\uf243")]
        fa_battery_1,
        [FontAwesomeCode("\uf243")]
        fa_battery_quarter,
        [FontAwesomeCode("\uf244")]
        fa_battery_0,
        [FontAwesomeCode("\uf244")]
        fa_battery_empty,
        [FontAwesomeCode("\uf245")]
        fa_mouse_pointer,
        [FontAwesomeCode("\uf246")]
        fa_i_cursor,
        [FontAwesomeCode("\uf247")]
        fa_object_group,
        [FontAwesomeCode("\uf248")]
        fa_object_ungroup,
        [FontAwesomeCode("\uf249")]
        fa_sticky_note,
        [FontAwesomeCode("\uf24a")]
        fa_sticky_note_o,
        [FontAwesomeCode("\uf24b")]
        fa_cc_jcb,
        [FontAwesomeCode("\uf24c")]
        fa_cc_diners_club,
        [FontAwesomeCode("\uf24d")]
        fa_clone,
        [FontAwesomeCode("\uf24e")]
        fa_balance_scale,
        [FontAwesomeCode("\uf250")]
        fa_hourglass_o,
        [FontAwesomeCode("\uf251")]
        fa_hourglass_1,
        [FontAwesomeCode("\uf251")]
        fa_hourglass_start,
        [FontAwesomeCode("\uf252")]
        fa_hourglass_2,
        [FontAwesomeCode("\uf252")]
        fa_hourglass_half,
        [FontAwesomeCode("\uf253")]
        fa_hourglass_3,
        [FontAwesomeCode("\uf253")]
        fa_hourglass_end,
        [FontAwesomeCode("\uf254")]
        fa_hourglass,
        [FontAwesomeCode("\uf255")]
        fa_hand_grab_o,
        [FontAwesomeCode("\uf255")]
        fa_hand_rock_o,
        [FontAwesomeCode("\uf256")]
        fa_hand_stop_o,
        [FontAwesomeCode("\uf256")]
        fa_hand_paper_o,
        [FontAwesomeCode("\uf257")]
        fa_hand_scissors_o,
        [FontAwesomeCode("\uf258")]
        fa_hand_lizard_o,
        [FontAwesomeCode("\uf259")]
        fa_hand_spock_o,
        [FontAwesomeCode("\uf25a")]
        fa_hand_pointer_o,
        [FontAwesomeCode("\uf25b")]
        fa_hand_peace_o,
        [FontAwesomeCode("\uf25c")]
        fa_trademark,
        [FontAwesomeCode("\uf25d")]
        fa_registered,
        [FontAwesomeCode("\uf25e")]
        fa_creative_commons,
        [FontAwesomeCode("\uf260")]
        fa_gg,
        [FontAwesomeCode("\uf261")]
        fa_gg_circle,
        [FontAwesomeCode("\uf262")]
        fa_tripadvisor,
        [FontAwesomeCode("\uf263")]
        fa_odnoklassniki,
        [FontAwesomeCode("\uf264")]
        fa_odnoklassniki_square,
        [FontAwesomeCode("\uf265")]
        fa_get_pocket,
        [FontAwesomeCode("\uf266")]
        fa_wikipedia_w,
        [FontAwesomeCode("\uf267")]
        fa_safari,
        [FontAwesomeCode("\uf268")]
        fa_chrome,
        [FontAwesomeCode("\uf269")]
        fa_firefox,
        [FontAwesomeCode("\uf26a")]
        fa_opera,
        [FontAwesomeCode("\uf26b")]
        fa_internet_explorer,
        [FontAwesomeCode("\uf26c")]
        fa_tv,
        [FontAwesomeCode("\uf26c")]
        fa_television,
        [FontAwesomeCode("\uf26d")]
        fa_contao,
        [FontAwesomeCode("\uf26e")]
        fa_500px,
        [FontAwesomeCode("\uf270")]
        fa_amazon,
        [FontAwesomeCode("\uf271")]
        fa_calendar_plus_o,
        [FontAwesomeCode("\uf272")]
        fa_calendar_minus_o,
        [FontAwesomeCode("\uf273")]
        fa_calendar_times_o,
        [FontAwesomeCode("\uf274")]
        fa_calendar_check_o,
        [FontAwesomeCode("\uf275")]
        fa_industry,
        [FontAwesomeCode("\uf276")]
        fa_map_pin,
        [FontAwesomeCode("\uf277")]
        fa_map_signs,
        [FontAwesomeCode("\uf278")]
        fa_map_o,
        [FontAwesomeCode("\uf279")]
        fa_map,
        [FontAwesomeCode("\uf27a")]
        fa_commenting,
        [FontAwesomeCode("\uf27b")]
        fa_commenting_o,
        [FontAwesomeCode("\uf27c")]
        fa_houzz,
        [FontAwesomeCode("\uf27d")]
        fa_vimeo,
        [FontAwesomeCode("\uf27e")]
        fa_black_tie,
        [FontAwesomeCode("\uf280")]
        fa_fonticons,
        [FontAwesomeCode("\uf281")]
        fa_reddit_alien,
        [FontAwesomeCode("\uf282")]
        fa_edge,
        [FontAwesomeCode("\uf283")]
        fa_credit_card_alt,
        [FontAwesomeCode("\uf284")]
        fa_codiepie,
        [FontAwesomeCode("\uf285")]
        fa_modx,
        [FontAwesomeCode("\uf286")]
        fa_fort_awesome,
        [FontAwesomeCode("\uf287")]
        fa_usb,
        [FontAwesomeCode("\uf288")]
        fa_product_hunt,
        [FontAwesomeCode("\uf289")]
        fa_mixcloud,
        [FontAwesomeCode("\uf28a")]
        fa_scribd,
        [FontAwesomeCode("\uf28b")]
        fa_pause_circle,
        [FontAwesomeCode("\uf28c")]
        fa_pause_circle_o,
        [FontAwesomeCode("\uf28d")]
        fa_stop_circle,
        [FontAwesomeCode("\uf28e")]
        fa_stop_circle_o,
        [FontAwesomeCode("\uf290")]
        fa_shopping_bag,
        [FontAwesomeCode("\uf291")]
        fa_shopping_basket,
        [FontAwesomeCode("\uf292")]
        fa_hashtag,
        [FontAwesomeCode("\uf293")]
        fa_bluetooth,
        [FontAwesomeCode("\uf294")]
        fa_bluetooth_b,
        [FontAwesomeCode("\uf295")]
        fa_percent,
        [FontAwesomeCode("\uf296")]
        fa_gitlab,
        [FontAwesomeCode("\uf297")]
        fa_wpbeginner,
        [FontAwesomeCode("\uf298")]
        fa_wpforms,
        [FontAwesomeCode("\uf299")]
        fa_envira,
        [FontAwesomeCode("\uf29a")]
        fa_universal_access,
        [FontAwesomeCode("\uf29b")]
        fa_wheelchair_alt,
        [FontAwesomeCode("\uf29c")]
        fa_question_circle_o,
        [FontAwesomeCode("\uf29d")]
        fa_blind,
        [FontAwesomeCode("\uf29e")]
        fa_audio_description,
        [FontAwesomeCode("\uf2a0")]
        fa_volume_control_phone,
        [FontAwesomeCode("\uf2a1")]
        fa_braille,
        [FontAwesomeCode("\uf2a2")]
        fa_assistive_listening_systems,
        [FontAwesomeCode("\uf2a3")]
        fa_asl_interpreting,
        [FontAwesomeCode("\uf2a3")]
        fa_american_sign_language_interpreting,
        [FontAwesomeCode("\uf2a4")]
        fa_deafness,
        [FontAwesomeCode("\uf2a4")]
        fa_hard_of_hearing,
        [FontAwesomeCode("\uf2a4")]
        fa_deaf,
        [FontAwesomeCode("\uf2a5")]
        fa_glide,
        [FontAwesomeCode("\uf2a6")]
        fa_glide_g,
        [FontAwesomeCode("\uf2a7")]
        fa_signing,
        [FontAwesomeCode("\uf2a7")]
        fa_sign_language,
        [FontAwesomeCode("\uf2a8")]
        fa_low_vision,
        [FontAwesomeCode("\uf2a9")]
        fa_viadeo,
        [FontAwesomeCode("\uf2aa")]
        fa_viadeo_square,
        [FontAwesomeCode("\uf2ab")]
        fa_snapchat,
        [FontAwesomeCode("\uf2ac")]
        fa_snapchat_ghost,
        [FontAwesomeCode("\uf2ad")]
        fa_snapchat_square,
        [FontAwesomeCode("\uf2ae")]
        fa_pied_piper,
        [FontAwesomeCode("\uf2b0")]
        fa_first_order,
        [FontAwesomeCode("\uf2b1")]
        fa_yoast,
        [FontAwesomeCode("\uf2b2")]
        fa_themeisle,
        [FontAwesomeCode("\uf2b3")]
        fa_google_plus_circle,
        [FontAwesomeCode("\uf2b3")]
        fa_google_plus_official,
        [FontAwesomeCode("\uf2b4")]
        fa_fa,
        [FontAwesomeCode("\uf2b4")]
        fa_font_awesome,
        [FontAwesomeCode("\uf2b5")]
        fa_handshake_o,
        [FontAwesomeCode("\uf2b6")]
        fa_envelope_open,
        [FontAwesomeCode("\uf2b7")]
        fa_envelope_open_o,
        [FontAwesomeCode("\uf2b8")]
        fa_linode,
        [FontAwesomeCode("\uf2b9")]
        fa_address_book,
        [FontAwesomeCode("\uf2ba")]
        fa_address_book_o,
        [FontAwesomeCode("\uf2bb")]
        fa_vcard,
        [FontAwesomeCode("\uf2bb")]
        fa_address_card,
        [FontAwesomeCode("\uf2bc")]
        fa_vcard_o,
        [FontAwesomeCode("\uf2bc")]
        fa_address_card_o,
        [FontAwesomeCode("\uf2bd")]
        fa_user_circle,
        [FontAwesomeCode("\uf2be")]
        fa_user_circle_o,
        [FontAwesomeCode("\uf2c0")]
        fa_user_o,
        [FontAwesomeCode("\uf2c1")]
        fa_id_badge,
        [FontAwesomeCode("\uf2c2")]
        fa_drivers_license,
        [FontAwesomeCode("\uf2c2")]
        fa_id_card,
        [FontAwesomeCode("\uf2c3")]
        fa_drivers_license_o,
        [FontAwesomeCode("\uf2c3")]
        fa_id_card_o,
        [FontAwesomeCode("\uf2c4")]
        fa_quora,
        [FontAwesomeCode("\uf2c5")]
        fa_free_code_camp,
        [FontAwesomeCode("\uf2c6")]
        fa_telegram,
        [FontAwesomeCode("\uf2c7")]
        fa_thermometer_4,
        [FontAwesomeCode("\uf2c7")]
        fa_thermometer,
        [FontAwesomeCode("\uf2c7")]
        fa_thermometer_full,
        [FontAwesomeCode("\uf2c8")]
        fa_thermometer_3,
        [FontAwesomeCode("\uf2c8")]
        fa_thermometer_three_quarters,
        [FontAwesomeCode("\uf2c9")]
        fa_thermometer_2,
        [FontAwesomeCode("\uf2c9")]
        fa_thermometer_half,
        [FontAwesomeCode("\uf2ca")]
        fa_thermometer_1,
        [FontAwesomeCode("\uf2ca")]
        fa_thermometer_quarter,
        [FontAwesomeCode("\uf2cb")]
        fa_thermometer_0,
        [FontAwesomeCode("\uf2cb")]
        fa_thermometer_empty,
        [FontAwesomeCode("\uf2cc")]
        fa_shower,
        [FontAwesomeCode("\uf2cd")]
        fa_bathtub,
        [FontAwesomeCode("\uf2cd")]
        fa_s15,
        [FontAwesomeCode("\uf2cd")]
        fa_bath,
        [FontAwesomeCode("\uf2ce")]
        fa_podcast,
        [FontAwesomeCode("\uf2d0")]
        fa_window_maximize,
        [FontAwesomeCode("\uf2d1")]
        fa_window_minimize,
        [FontAwesomeCode("\uf2d2")]
        fa_window_restore,
        [FontAwesomeCode("\uf2d3")]
        fa_times_rectangle,
        [FontAwesomeCode("\uf2d3")]
        fa_window_close,
        [FontAwesomeCode("\uf2d4")]
        fa_times_rectangle_o,
        [FontAwesomeCode("\uf2d4")]
        fa_window_close_o,
        [FontAwesomeCode("\uf2d5")]
        fa_bandcamp,
        [FontAwesomeCode("\uf2d6")]
        fa_grav,
        [FontAwesomeCode("\uf2d7")]
        fa_etsy,
        [FontAwesomeCode("\uf2d8")]
        fa_imdb,
        [FontAwesomeCode("\uf2d9")]
        fa_ravelry,
        [FontAwesomeCode("\uf2da")]
        fa_eercast,
        [FontAwesomeCode("\uf2db")]
        fa_microchip,
        [FontAwesomeCode("\uf2dc")]
        fa_snowflake_o,
        [FontAwesomeCode("\uf2dd")]
        fa_superpowers,
        [FontAwesomeCode("\uf2de")]
        fa_wpexplorer,
        [FontAwesomeCode("\uf2e0")]
        fa_meetup,

    }

}